Update to 2.0.2
SUSE/registry pull request #29
Opened 2020-08-19 09:11 UTC by dirkmueller

2020-08-19 14:16 UTC, stefannica requested changes
Overall, looks good, but you should include the revision numbers in the helm chart image tags, or at least explain why you don't think they are needed anymore.

2020-08-19 14:16 UTC, stefannica commented on harbor-helm/values.yaml
> -    tag: 2.0.1-rev1
You should keep the `rev1` bit.

2020-08-19 14:16 UTC, stefannica commented on harbor-helm/values.yaml
> -    tag: 2.0.1-rev1
Same here: keep the `rev1` bit.

2020-08-20 13:53 UTC, dirkmueller commented on harbor-helm/values.yaml
> -    tag: 2.0.1-rev1
done

2020-08-20 13:53 UTC, dirkmueller commented on harbor-helm/values.yaml
> -    tag: 2.0.1-rev1
done

2020-08-20 14:14 UTC, stefannica approved these changes

2020-08-20 14:14 UTC, merged