Add missing registry/controller image to values-dev
SUSE/registry pull request #41
Opened 2020-09-01 14:16 UTC by flaviodsr

The entry for the registry controller image is missing on
values-dev.yaml file.

(cherry picked from commit d3813bd7aea28d8ddda715e5c3eece4cbdd8a3bf)

2020-09-01 19:00 UTC, stefannica requested changes

2020-09-01 19:00 UTC, stefannica commented on harbor-helm/values-dev.yaml
> +      repository: rregistry.suse.de/devel/caps/registry/containers/registry/harbor-registryctl
There's a typo: `rregistry`

2020-09-02 08:18 UTC, flaviodsr commented on harbor-helm/values-dev.yaml
> +      repository: rregistry.suse.de/devel/caps/registry/containers/registry/harbor-registryctl
fixed, thank you!

2020-09-02 08:28 UTC, stefannica approved these changes

2020-09-02 08:29 UTC, merged