Enable notary support
SUSE/registry pull request #44
Opened 2020-09-08 06:33 UTC by jsuchome

Point to SLES based images

2020-09-08 07:12 UTC, jsuchome commented
Do not merge until the images are built and published...

2020-09-08 07:50 UTC, stefannica submitted a review, later dismissed

2020-09-08 16:22 UTC, flaviodsr requested changes
Functionality wise the change is good, I have tested and signing images works. However I think the name of the images are not right...

2020-09-08 17:49 UTC, jsuchome commented on harbor-helm/values.yaml
> +      repository: registry.suse.com/registry/notary-server
good point

2020-09-09 08:22 UTC, flaviodsr approved these changes

2020-10-01 11:46 UTC, stefannica commented
Closing in favor of #58

2020-10-01 11:46 UTC, closed without merging