add periodic 2.1 job
SUSE/registry pull request #54
Opened 2020-09-29 14:09 UTC by dirkmueller

2020-09-29 15:16 UTC, stefannica reviewed
+1 from me, but I'll leave it for @flaviodsr to approve

2020-09-29 15:49 UTC, flaviodsr requested changes
I have tested this on my fork and with the suggested changes the workflow should be fine.

2020-09-29 15:49 UTC, flaviodsr commented on .github/workflows/periodic-21.yml
> +          expose:
```suggestion
          cat << EOF | tee ${NAMESPACE}.yaml
          suse:
            AcceptBetaEULA: "yes"
          expose:
```

2020-09-29 15:49 UTC, flaviodsr commented on .github/workflows/periodic-21.yml
> +          # replace images repository according to source
```suggestion
        run: |
          chart="./harbor"
          rm -rf ${chart}
          helm chart pull ${{ matrix.install_src }}/charts/registry/harbor:latest
          helm chart export ${{ matrix.install_src }}/charts/registry/harbor:latest
          # replace images repository according to source
```

2020-09-29 15:49 UTC, flaviodsr commented on .github/workflows/periodic-21.yml
> +          # replace images repository according to source
```suggestion
        run: |
          chart="./harbor"
          rm -rf ${chart}
          helm chart pull ${{ matrix.upgrade_src }}/charts/registry/harbor:latest
          helm chart export ${{ matrix.upgrade_src }}/charts/registry/harbor:latest
          # replace images repository according to source
```

2020-09-29 15:49 UTC, flaviodsr commented on .github/workflows/periodic-21.yml
> +              echo "::set-env name=NAMESPACE::spr20-sched-${{ matrix.source }}"
```suggestion
              echo "::set-env name=NAMESPACE::spr21-sched-${{ matrix.source }}"
```

2020-09-29 15:49 UTC, flaviodsr commented on .github/workflows/periodic-21.yml
> +          # replace images repository according to source
This is required to remove the chart pulled by the previous run

2020-09-29 15:49 UTC, flaviodsr commented on .github/workflows/periodic-21.yml
> +          # replace images repository according to source
same here

2020-09-30 11:28 UTC, flaviodsr approved these changes
LGTM

2020-09-30 18:00 UTC, merged